title: "Collage Maker"
description: "Professional photo collage creation tool with 15+ artistic styles"
url: "https://nipunbatra.github.io/collage-maker"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

header_pages:
  - index.md
  - MODULAR_SYSTEM.md

google_analytics: # Add your GA tracking ID if desired

social_links:
  github: nipunbatra/collage-maker

author:
  name: Nipun Batra
  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"