name: Deploy Quarto site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Render site
        run: |
          cd docs
          quarto render
          
      - name: List generated files
        run: |
          echo "Checking for generated files:"
          ls -la docs/
          echo "Looking for _site directory:"
          find docs -name "_site" -type d || echo "No _site directory found"
          echo "All HTML files:"
          find docs -name "*.html" -type f || echo "No HTML files found"
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site
          
      - name: Upload site as artifact for debugging
        uses: actions/upload-artifact@v4
        with:
          name: quarto-site
          path: ./docs/_site
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4